export default {
  en: [
    [
      { label: '`', secondLabel: '~', keyCode: 'Backquote' },
      { label: '1', secondLabel: '!', keyCode: 'Digit1' },
      { label: '2', secondLabel: '@', keyCode: 'Digit2' },
      { label: '3', secondLabel: '#', keyCode: 'Digit3' },
      { label: '4', secondLabel: '$', keyCode: 'Digit4' },
      { label: '5', secondLabel: '%', keyCode: 'Digit5' },
      { label: '6', secondLabel: '^', keyCode: 'Digit6' },
      { label: '7', secondLabel: '&', keyCode: 'Digit7' },
      { label: '8', secondLabel: '*', keyCode: 'Digit8' },
      { label: '9', secondLabel: '(', keyCode: 'Digit9' },
      { label: '0', secondLabel: ')', keyCode: 'Digit0' },
      { label: '-', secondLabel: '_', keyCode: 'Minus' },
      { label: '=', secondLabel: '+', keyCode: 'Equal' },
      { label: '← Backspace', keyCode: 'Backspace' },
    ],
    [
      { label: 'Tab ⇄', keyCode: 'Tab' },
      { label: 'Q', keyCode: 'KeyQ', isCaseSensitive: true },
      { label: 'W', keyCode: 'KeyW', isCaseSensitive: true },
      { label: 'E', keyCode: 'KeyE', isCaseSensitive: true },
      { label: 'R', keyCode: 'KeyR', isCaseSensitive: true },
      { label: 'T', keyCode: 'KeyT', isCaseSensitive: true },
      { label: 'Y', keyCode: 'KeyY', isCaseSensitive: true },
      { label: 'U', keyCode: 'KeyU', isCaseSensitive: true },
      { label: 'I', keyCode: 'KeyI', isCaseSensitive: true },
      { label: 'O', keyCode: 'KeyO', isCaseSensitive: true },
      { label: 'P', keyCode: 'KeyP', isCaseSensitive: true },
      { label: '[', secondLabel: '{', keyCode: 'BracketLeft' },
      { label: ']', secondLabel: '}', keyCode: 'BracketRight' },
      { label: 'Delele', keyCode: 'Delele' },
    ],
    [
      { label: 'CapsLock', keyCode: 'CapsLock' },
      { label: 'A', keyCode: 'KeyA', isCaseSensitive: true },
      { label: 'S', keyCode: 'KeyS', isCaseSensitive: true },
      { label: 'D', keyCode: 'KeyD', isCaseSensitive: true },
      { label: 'F', keyCode: 'KeyF', isCaseSensitive: true },
      { label: 'G', keyCode: 'KeyG', isCaseSensitive: true },
      { label: 'H', keyCode: 'KeyH', isCaseSensitive: true },
      { label: 'J', keyCode: 'KeyJ', isCaseSensitive: true },
      { label: 'K', keyCode: 'KeyK', isCaseSensitive: true },
      { label: 'L', keyCode: 'KeyL', isCaseSensitive: true },
      { label: ';', secondLabel: ':', keyCode: 'Semicolon' },
      { label: "'", secondLabel: '"', keyCode: 'Quote' },
      { label: 'Enter', keyCode: 'Enter' },
    ],
    [
      { label: 'Shift', keyCode: 'ShiftLeft' },
      { label: '\\', secondLabel: '|', keyCode: 'Backslash' },
      { label: 'Z', keyCode: 'KeyZ', isCaseSensitive: true },
      { label: 'X', keyCode: 'KeyX', isCaseSensitive: true },
      { label: 'C', keyCode: 'KeyC', isCaseSensitive: true },
      { label: 'V', keyCode: 'KeyV', isCaseSensitive: true },
      { label: 'B', keyCode: 'KeyB', isCaseSensitive: true },
      { label: 'N', keyCode: 'KeyN', isCaseSensitive: true },
      { label: 'M', keyCode: 'KeyM', isCaseSensitive: true },
      { label: ',', secondLabel: '<', keyCode: 'Comma' },
      { label: '.', secondLabel: '>', keyCode: 'Period' },
      { label: '/', secondLabel: '?', keyCode: 'Slash' },
      { label: '↑', keyCode: 'ArrowUp' },
      { label: 'Shift', keyCode: 'ShiftRight' },
    ],
    [
      { label: 'Ctrl', keyCode: 'ControlLeft' },
      { label: '⊞', keyCode: 'MetaLeft' },
      { label: '🌐', keyCode: 'ChangeLanguage' },
      { label: 'Alt', keyCode: 'AltLeft' },
      { label: '', keyCode: 'Space' },
      { label: 'Alt', keyCode: 'AltRight' },
      { label: 'Ctrl', keyCode: 'ControlRight' },
      { label: '←', keyCode: 'ArrowLeft' },
      { label: '↓', keyCode: 'ArrowDown' },
      { label: '→', keyCode: 'ArrowRight' },
    ],
  ],
  ru: [
    [
      { label: 'Ё', keyCode: 'Backquote', isCaseSensitive: true },
      { label: '1', secondLabel: '!', keyCode: 'Digit1' },
      { label: '2', secondLabel: '"', keyCode: 'Digit2' },
      { label: '3', secondLabel: '№', keyCode: 'Digit3' },
      { label: '4', secondLabel: ';', keyCode: 'Digit4' },
      { label: '5', secondLabel: '%', keyCode: 'Digit5' },
      { label: '6', secondLabel: ':', keyCode: 'Digit6' },
      { label: '7', secondLabel: '?', keyCode: 'Digit7' },
      { label: '8', secondLabel: '*', keyCode: 'Digit8' },
      { label: '9', secondLabel: '(', keyCode: 'Digit9' },
      { label: '0', secondLabel: ')', keyCode: 'Digit0' },
      { label: '-', secondLabel: '_', keyCode: 'Minus' },
      { label: '=', secondLabel: '+', keyCode: 'Equal' },
      { label: '← Backspace', keyCode: 'Backspace' },
    ],
    [
      { label: 'Tab ⇄', keyCode: 'Tab' },
      { label: 'Й', keyCode: 'KeyQ', isCaseSensitive: true },
      { label: 'Ц', keyCode: 'KeyW', isCaseSensitive: true },
      { label: 'У', keyCode: 'KeyE', isCaseSensitive: true },
      { label: 'К', keyCode: 'KeyR', isCaseSensitive: true },
      { label: 'Е', keyCode: 'KeyT', isCaseSensitive: true },
      { label: 'Н', keyCode: 'KeyY', isCaseSensitive: true },
      { label: 'Г', keyCode: 'KeyU', isCaseSensitive: true },
      { label: 'Ш', keyCode: 'KeyI', isCaseSensitive: true },
      { label: 'Щ', keyCode: 'KeyO', isCaseSensitive: true },
      { label: 'З', keyCode: 'KeyP', isCaseSensitive: true },
      { label: 'Х', keyCode: 'BracketLeft', isCaseSensitive: true },
      { label: 'Ъ', keyCode: 'BracketRight', isCaseSensitive: true },
      { label: 'Delele', keyCode: 'Delele' },
    ],
    [
      { label: 'CapsLock', keyCode: 'CapsLock' },
      { label: 'Ф', keyCode: 'KeyA', isCaseSensitive: true },
      { label: 'Ы', keyCode: 'KeyS', isCaseSensitive: true },
      { label: 'В', keyCode: 'KeyD', isCaseSensitive: true },
      { label: 'А', keyCode: 'KeyF', isCaseSensitive: true },
      { label: 'П', keyCode: 'KeyG', isCaseSensitive: true },
      { label: 'Р', keyCode: 'KeyH', isCaseSensitive: true },
      { label: 'О', keyCode: 'KeyJ', isCaseSensitive: true },
      { label: 'Л', keyCode: 'KeyK', isCaseSensitive: true },
      { label: 'Д', keyCode: 'KeyL', isCaseSensitive: true },
      { label: 'Ж', keyCode: 'Semicolon', isCaseSensitive: true },
      { label: 'Э', keyCode: 'Quote', isCaseSensitive: true },
      { label: 'Enter', keyCode: 'Enter' },
    ],
    [
      { label: 'Shift', keyCode: 'ShiftLeft' },
      { label: '\\', secondLabel: '|', keyCode: 'Backslash' },
      { label: 'Я', keyCode: 'KeyZ', isCaseSensitive: true },
      { label: 'Ч', keyCode: 'KeyX', isCaseSensitive: true },
      { label: 'С', keyCode: 'KeyC', isCaseSensitive: true },
      { label: 'М', keyCode: 'KeyV', isCaseSensitive: true },
      { label: 'И', keyCode: 'KeyB', isCaseSensitive: true },
      { label: 'Т', keyCode: 'KeyN', isCaseSensitive: true },
      { label: 'Ь', keyCode: 'KeyM', isCaseSensitive: true },
      { label: 'Б', keyCode: 'Comma', isCaseSensitive: true },
      { label: 'Ю', keyCode: 'Period', isCaseSensitive: true },
      { label: '.', secondLabel: ',', keyCode: 'Slash' },
      { label: '↑', keyCode: 'ArrowUp' },
      { label: 'Shift', keyCode: 'ShiftRight' },
    ],
    [
      { label: 'Ctrl', keyCode: 'ControlLeft' },
      { label: '⊞', keyCode: 'MetaLeft' },
      { label: '🌐', keyCode: 'ChangeLanguage' },
      { label: 'Alt', keyCode: 'AltLeft' },
      { label: '', keyCode: 'Space' },
      { label: 'Alt', keyCode: 'AltRight' },
      { label: 'Ctrl', keyCode: 'ControlRight' },
      { label: '←', keyCode: 'ArrowLeft' },
      { label: '↓', keyCode: 'ArrowDown' },
      { label: '→', keyCode: 'ArrowRight' },
    ],
  ],
};
